version: "3.7"
services:
    bot:
        build: build
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
        command: ["./bot"]


    db: 
        build: database
        ports: 
            - 5432:5432

        volumes:
            - database:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
  
volumes:
    database:    